---

# Main tasks file for odoo role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::odoo'
    - 'role::odoo::init'
